const ASSETS = [
  {
    id: 1,
    category: "IT",
    assetName: "OA",
    ip: "10.150.20.11",
    mac: "00:50:56:8E:1F:7A",
    hostname: "FSVMGR001",
    os: "Windows Server 2016 Standard",
    model: "VMware Virtual",
    manageDept: "정보보안팀",
    manager: "홍길동",
    operator: "김운영",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: true, eps: true, dlp: false, drm: true, nac: true, pms: true,
  },
  {
    id: 2,
    category: "IT",
    assetName: "OA",
    ip: "10.150.20.12",
    mac: "00:50:56:8E:2A:3B",
    hostname: "FSVMGR002",
    os: "Windows Server 2019 Standard",
    model: "VMware Virtual",
    manageDept: "정보보안팀",
    manager: "홍길동",
    operator: "김운영",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: true, eps: true, dlp: false, drm: true, nac: true, pms: true,
  },
  {
    id: 3,
    category: "IT",
    assetName: "OA",
    ip: "10.150.21.10",
    mac: "B4:2E:99:1D:5C:AA",
    hostname: "WEB-SRV001",
    os: "CentOS Linux 7",
    model: "Dell PowerEdge R640",
    manageDept: "인프라팀",
    manager: "이서버",
    operator: "박운영",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: true, eps: false, dlp: false, drm: false, nac: true, pms: true,
  },
  {
    id: 4,
    category: "IT",
    assetName: "OA",
    ip: "10.150.21.11",
    mac: "B4:2E:99:1D:5C:BB",
    hostname: "WEB-SRV002",
    os: "CentOS Linux 7",
    model: "Dell PowerEdge R640",
    manageDept: "인프라팀",
    manager: "이서버",
    operator: "박운영",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: true, eps: false, dlp: false, drm: false, nac: true, pms: true,
  },
  {
    id: 5,
    category: "IT",
    assetName: "OA",
    ip: "10.150.22.5",
    mac: "C8:5B:76:4E:11:22",
    hostname: "DB-SRV001",
    os: "Windows Server 2019 Standard",
    model: "HP ProLiant DL380 Gen10",
    manageDept: "인프라팀",
    manager: "이서버",
    operator: "최DB",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: true, eps: true, dlp: true, drm: true, nac: true, pms: true,
  },
  {
    id: 6,
    category: "IT",
    assetName: "OA",
    ip: "10.150.30.101",
    mac: "40:8D:5C:A2:B3:C4",
    hostname: "PC-INFOSEC-001",
    os: "Windows 11 Pro",
    model: "Samsung Galaxy Book4",
    manageDept: "정보보안팀",
    manager: "홍길동",
    operator: "홍길동",
    status: "운영중",
    location: "본관 4층 보안팀",
    edr: true, eps: true, dlp: true, drm: true, nac: true, pms: true,
  },
  {
    id: 7,
    category: "IT",
    assetName: "OA",
    ip: "10.150.30.102",
    mac: "40:8D:5C:A2:B3:D5",
    hostname: "PC-INFOSEC-002",
    os: "Windows 11 Pro",
    model: "Samsung Galaxy Book4",
    manageDept: "정보보안팀",
    manager: "홍길동",
    operator: "김보안",
    status: "운영중",
    location: "본관 4층 보안팀",
    edr: true, eps: true, dlp: true, drm: true, nac: true, pms: true,
  },
  {
    id: 8,
    category: "IT",
    assetName: "OA",
    ip: "10.150.40.55",
    mac: "DC:A6:32:5B:11:FF",
    hostname: "PC-HR-001",
    os: "Windows 10 Pro",
    model: "LG gram 16",
    manageDept: "인사팀",
    manager: "정인사",
    operator: "정인사",
    status: "운영중",
    location: "본관 2층 인사팀",
    edr: true, eps: true, dlp: true, drm: true, nac: true, pms: false,
  },
  {
    id: 9,
    category: "IT",
    assetName: "OA",
    ip: "10.150.50.10",
    mac: "00:1B:21:AA:BB:CC",
    hostname: "BACKUP-SRV001",
    os: "Windows Server 2022 Standard",
    model: "IBM System x3550 M5",
    manageDept: "인프라팀",
    manager: "이서버",
    operator: "오백업",
    status: "운영중",
    location: "별관 지하 1층 DR센터",
    edr: true, eps: true, dlp: false, drm: false, nac: true, pms: true,
  },
  {
    id: 10,
    category: "IT",
    assetName: "OA",
    ip: "10.150.60.200",
    mac: "E4:5D:37:C1:AA:11",
    hostname: "MAIL-SRV001",
    os: "Windows Server 2019 Standard",
    model: "Dell PowerEdge R440",
    manageDept: "인프라팀",
    manager: "이서버",
    operator: "나메일",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: true, eps: true, dlp: false, drm: false, nac: true, pms: true,
  },
  {
    id: 11,
    category: "IT",
    assetName: "OA",
    ip: "10.150.70.15",
    mac: "00:25:90:CC:DD:EE",
    hostname: "NAS-SRV001",
    os: "Synology DSM 7.2",
    model: "Synology RS3621xs+",
    manageDept: "인프라팀",
    manager: "이서버",
    operator: "박운영",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: false, eps: false, dlp: false, drm: false, nac: true, pms: false,
  },
  {
    id: 12,
    category: "IT",
    assetName: "OA",
    ip: "10.150.80.5",
    mac: "F4:8E:38:D4:E5:11",
    hostname: "VPN-GW001",
    os: "FortiOS 7.4",
    model: "FortiGate 200F",
    manageDept: "정보보안팀",
    manager: "홍길동",
    operator: "김운영",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: false, eps: false, dlp: false, drm: false, nac: false, pms: false,
  },
  {
    id: 13,
    category: "OT",
    assetName: "FA",
    ip: "10.160.10.5",
    mac: "00:0C:29:FA:01:A1",
    hostname: "SCADA-SRV001",
    os: "Windows Server 2012 R2",
    model: "Siemens SIMATIC PC",
    manageDept: "생산관리팀",
    manager: "강생산",
    operator: "신공장",
    status: "운영중",
    location: "제1공장 제어실",
    edr: true, eps: false, dlp: false, drm: false, nac: false, pms: false,
  },
  {
    id: 14,
    category: "OT",
    assetName: "FA",
    ip: "10.160.10.6",
    mac: "00:0C:29:FA:01:B2",
    hostname: "SCADA-SRV002",
    os: "Windows Server 2012 R2",
    model: "Siemens SIMATIC PC",
    manageDept: "생산관리팀",
    manager: "강생산",
    operator: "신공장",
    status: "운영중",
    location: "제1공장 제어실",
    edr: true, eps: false, dlp: false, drm: false, nac: false, pms: false,
  },
  {
    id: 15,
    category: "OT",
    assetName: "FA",
    ip: "10.160.20.3",
    mac: "00:80:F4:0B:CC:DD",
    hostname: "HMI-001",
    os: "Windows 10 IoT Enterprise",
    model: "Advantech IPC-7132",
    manageDept: "설비관리팀",
    manager: "유설비",
    operator: "신공장",
    status: "운영중",
    location: "제2공장 현장",
    edr: false, eps: false, dlp: false, drm: false, nac: false, pms: false,
  },
  {
    id: 16,
    category: "OT",
    assetName: "FA",
    ip: "10.160.20.4",
    mac: "00:80:F4:0B:CC:EE",
    hostname: "HMI-002",
    os: "Windows 10 IoT Enterprise",
    model: "Advantech IPC-7132",
    manageDept: "설비관리팀",
    manager: "유설비",
    operator: "신공장",
    status: "운영중",
    location: "제2공장 현장",
    edr: false, eps: false, dlp: false, drm: false, nac: false, pms: false,
  },
  {
    id: 17,
    category: "OT",
    assetName: "FA",
    ip: "10.160.30.1",
    mac: "00:0D:3A:1F:22:33",
    hostname: "PLC-LINE1",
    os: "Embedded (PLC)",
    model: "Mitsubishi MELSEC iQ-R",
    manageDept: "설비관리팀",
    manager: "유설비",
    operator: "김PLC",
    status: "운영중",
    location: "제1공장 라인 1",
    edr: false, eps: false, dlp: false, drm: false, nac: false, pms: false,
  },
  {
    id: 18,
    category: "OT",
    assetName: "FA",
    ip: "10.160.30.2",
    mac: "00:0D:3A:1F:22:44",
    hostname: "PLC-LINE2",
    os: "Embedded (PLC)",
    model: "Mitsubishi MELSEC iQ-R",
    manageDept: "설비관리팀",
    manager: "유설비",
    operator: "김PLC",
    status: "운영중",
    location: "제1공장 라인 2",
    edr: false, eps: false, dlp: false, drm: false, nac: false, pms: false,
  },
  {
    id: 19,
    category: "OT",
    assetName: "FA",
    ip: "10.160.40.10",
    mac: "AC:DE:48:11:22:33",
    hostname: "HIST-SRV001",
    os: "Windows Server 2016 Standard",
    model: "HP ProLiant DL20 Gen10",
    manageDept: "생산관리팀",
    manager: "강생산",
    operator: "박이력",
    status: "운영중",
    location: "제1공장 제어실",
    edr: true, eps: false, dlp: false, drm: false, nac: false, pms: true,
  },
  {
    id: 20,
    category: "IT",
    assetName: "OA",
    ip: "10.150.90.100",
    mac: "00:50:56:C0:00:08",
    hostname: "ESX-HOST001",
    os: "VMware ESXi 8.0",
    model: "Dell PowerEdge R750",
    manageDept: "인프라팀",
    manager: "이서버",
    operator: "박운영",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: false, eps: false, dlp: false, drm: false, nac: false, pms: true,
  },
  {
    id: 21,
    category: "IT",
    assetName: "OA",
    ip: "10.150.100.50",
    mac: "3C:FD:FE:12:34:56",
    hostname: "SIEM-SRV001",
    os: "Ubuntu 22.04 LTS",
    model: "HP ProLiant DL360 Gen10",
    manageDept: "정보보안팀",
    manager: "홍길동",
    operator: "김보안",
    status: "운영중",
    location: "본관 3층 전산실",
    edr: true, eps: false, dlp: false, drm: false, nac: true, pms: true,
  },
  {
    id: 22,
    category: "OT",
    assetName: "FA",
    ip: "10.160.50.5",
    mac: "00:17:7C:AB:CD:EF",
    hostname: "ENG-WS001",
    os: "Windows 10 Pro",
    model: "Dell Precision 3660",
    manageDept: "설비관리팀",
    manager: "유설비",
    operator: "최엔지니어",
    status: "운영중",
    location: "제2공장 엔지니어링실",
    edr: true, eps: true, dlp: false, drm: false, nac: false, pms: true,
  },
];
